### ISSUE TITLE
How login to the Mastadon Clone?

### ISSUE THREAD

**Issue by jacobfranco** [redplanetlabs/twitter-scale-mastodon#1]
Perhaps this is a silly question, but I followed the instructions and cloned both the mastadon repo and soapbox repo and started both of them.  I am getting a few errors upon startup, but I dont think they're the issue, or at least I don't think they're related.  I am met with a homepage that just says "Registration is closed".  I have the option to log in but I don't know what username or password there would be.

**Comment by nathanmarz** [comment]
Was the answer in rama-user helpful or do you need more help with this? If the API server isn't launching correctly, it would be helpful to see its log output.
