### ISSUE TITLE
getting error - java.lang.Error: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by dipenappscrip** [redplanetlabs/twitter-scale-mastodon#2]
In api/ folder I run  cmd - mvn spring-boot:run 
and i am getting this error -  java.lang.Error: java.lang.StackOverflowError
I am using Ubuntu OS

`:/home/ubuntu/rama/twitter-scale-mastodon/api# mvn spring-boot:run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< com.rpl:mastodonapi >-------------------------
[INFO] Building mastodonapi 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.7.7:run (default-cli) > test-compile @ mastodonapi >>>
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ mastodonapi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 30 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ mastodonapi ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ mastodonapi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /home/ubuntu/rama/twitter-scale-mastodon/api/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ mastodonapi ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< spring-boot-maven-plugin:2.7.7:run (default-cli) < test-compile @ mastodonapi <<<
[INFO]
[INFO]
[INFO] --- spring-boot-maven-plugin:2.7.7:run (default-cli) @ mastodonapi ---
[INFO] Attaching agents: []

07:25:25.737 INFO  [main] eplication.inspector - Inspector starting...
07:25:25.873 INFO  [main] keeper.inproc-server - Starting inprocess zookeeper {:port 41249, :dir /tmp/ipc14619169385988973085/zookeeper}
07:25:25.955 INFO  [main] ted.daemon.conductor - Starting Conductor...
07:25:26.463 INFO  [Conductor-bootstrap-0] per.zookeeper-client - create-node! {:path /current-rama-version}
07:25:26.504 INFO  [Conductor-bootstrap-0] per.zookeeper-client - create-node! {:path /version}
07:25:26.506 INFO  [Conductor-bootstrap-0] per.zookeeper-client - create-node! {:path /version/0.9.1}
07:25:26.507 INFO  [Conductor-bootstrap-0] per.zookeeper-client - create-node! {:path /version/0.9.1/modules}
07:25:26.511 INFO  [Conductor-bootstrap-0] per.zookeeper-client - create-node! {:path /version/0.9.1/conductor}
07:25:26.513 INFO  [Conductor-bootstrap-0] per.zookeeper-client - create-node! {:path /version/0.9.1/supervisors}
07:25:26.516 INFO  [Conductor-bootstrap-0] per.zookeeper-client - create-node! {:path /available-versions}
07:25:26.865 INFO  [Conductor-engine-0] ductor-state-machine - -before-handler []
07:25:26.911 INFO  [Conductor-bootstrap-0] ted.daemon.conductor - Conductor started successfully!
07:25:26.924 INFO  [Conductor-engine-0] per.zookeeper-client - create-node! {:path /version/0.9.1/conductor/state}
07:25:27.017 INFO  [Conductor-engine-0] ductor-state-machine - after-handler {:state [cluster-starting]}
07:25:27.102 INFO  [Conductor-engine-0] ductor-state-machine - -before-handler [cluster-starting]
07:25:27.164 INFO  [Conductor-engine-0] ductor-state-machine - Transitioning to CLUSTER-STARTING-TASKS. Preparing tasks for open...
07:25:27.171 INFO  [Conductor-engine-0] per.zookeeper-client - create-node! {:path /version/0.9.1/conductor/permit-worker-run-flag}
07:25:27.202 INFO  [Conductor-engine-0] ductor-state-machine - after-handler {:state [cluster-starting-tasks]}
07:25:27.296 INFO  [Conductor-engine-0] ductor-state-machine - -before-handler [cluster-starting-tasks]
07:25:27.299 INFO  [Conductor-engine-0] ductor-state-machine - Transitioning to CONDUCTOR-OPEN
07:25:27.328 INFO  [Conductor-engine-0] ductor-state-machine - after-handler {:state [conductor-open]}
07:25:27.445 INFO  [Conductor-bootstrap-0] ed.daemon.supervisor - Starting Supervisor... {:overrides {:throwable-handler #<StrictThrowableHandler{:init {:unexpected-throwables-vol #object[clojure.lang.Volatile 0x765ad49d {:status :ready, :val nil}], :expected-throwables #{java.lang.InterruptedException rpl.rama.distributed.exceptions.IntentionalFailureException}}, :generated {}}>, :time-source #object[rpl.rama.util.time_source.SystemTimeSource 0x128eeaa4 rpl.rama.util.time_source.SystemTimeSource@128eeaa4], :random-seed 1, :zk-client #rpl.rama.distributed.util.zookeeper.real_zookeeper_client.RealZookeeperClient{:internal? true, :label nil, :curator nil, :triggers-atom nil, :closeables-atom nil, :healthy?-atom nil}, :executor-service-factory #rpl.rama.util.exec_serv.IndependentFactory{}, :halt-on-unhealthy? false, :worker-supervision #<SimulatedWorkerSupervision{:init {:sim-processes-atom #object[clojure.lang.Atom 0x50b21d72 {:status :ready, :val {}}]}, :generated {:launch-count-atom nil, :worker-systems-by-port-atom nil}}>, :worker-overrides #rpl.rama.distributed.util.rama_component.compose.Merge{:a #rpl.rama.distributed.util.rama_component.compose.Merge{:a {:pid-getter #object[rpl.rama.distributed.simulate.discrete_daemon_deployment$base_worker_overrides$fn__344191 0x268787c9 rpl.rama.distributed.simulate.discrete_daemon_deployment$base_worker_overrides$fn__344191@268787c9], :module-manifest-loader #object[rpl.rama.distributed.simulate.sim_common$load_simulated_manifest 0x65941b8 rpl.rama.distributed.simulate.sim_common$load_simulated_manifest@65941b8], :weft-client #<UnifiedWeftClient{:init {}, :generated {:executor-service nil, :weft-metastore nil, :active-transfers-atom nil}}>}, :b {:replication-inspector-collector #rpl.rama.distributed.util.rama_component.core.OneTimeComponent{:start-fn #object[rpl.rama.distributed.simulate.discrete_daemon_deployment$start_supervisor_STAR_$fn__344202 0x63e7501d rpl.rama.distributed.simulate.discrete_daemon_deployment$start_supervisor_STAR_$fn__344202@63e7501d]}}}, :b {:zk-server-stats-fn #object[rpl.rama.distributed.util.helpers$zk_server_stats 0x23fe889e rpl.rama.distributed.util.helpers$zk_server_stats@23fe889e]}}, :label supervisor-supervisor-0, :recorder #<NoOpSimRecorder{:init {}, :generated {}}>, :random-source #object[java.util.Random 0x395dfae7 java.util.Random@395dfae7], :sync-module-code #object[rpl.rama.distributed.simulate.inproc_cluster$mk_in_process_deployment$fn__345714 0x75c528f5 rpl.rama.distributed.simulate.inproc_cluster$mk_in_process_deployment$fn__345714@75c528f5], :netty-factory #rpl.rama.distributed.worp.core.common.LocalNettyFactory{}}}
07:25:27.616 INFO  [supervisor-supervisor-0-exec-0] per.zookeeper-client - create-node! {:path /version/0.9.1/supervisors/supervisor-0}
07:25:27.712 INFO  [supervisor-supervisor-0-bootstrap-0] ed.daemon.supervisor - Started supervisor!
07:25:36.975 ERROR [main] NIOServerCnxnFactory - Thread Thread[main,5,main] died
java.lang.Error: java.lang.StackOverflowError
        at rpl.rama.util.exception$fn__24929.invokeStatic(exception.clj:74)
        at rpl.rama.util.exception$fn__24929.invoke(exception.clj:74)
        at rpl.rama.util.exception$fn__24916$G__24911__24921.invoke(exception.clj:71)
        at rpl.rama.util.helpers$deref_BANG_.invokeStatic(helpers.clj:1131)
        at rpl.rama.util.helpers$deref_BANG_.invoke(helpers.clj:1119)
        at rpl.rama.util.helpers$deref_BANG_.invokeStatic(helpers.clj:1125)
        at rpl.rama.util.helpers$deref_BANG_.invoke(helpers.clj:1119)
        at rpl.rama.distributed.simulate.inproc_cluster.IPC.cluster_deploy_modules_BANG_(inproc_cluster.clj:137)
        at rpl.rama.api4.cluster$cluster_launch_module_BANG_.invokeStatic(cluster.clj:117)
        at rpl.rama.api4.cluster$cluster_launch_module_BANG_.invoke(cluster.clj:112)
        at rpl.rama.java_api.ipc$mk_ipc$reify__366267$fn__366268.invoke(ipc.clj:96)
        at clojure.core$with_redefs_fn.invokeStatic(core.clj:7582)
        at clojure.core$with_redefs_fn.invoke(core.clj:7566)
        at rpl.rama.java_api.ipc$mk_ipc$reify__366267.launchModule(ipc.clj:94)
        at com.rpl.mastodonapi.MastodonApiApplication.initIPC(MastodonApiApplication.java:65)
        at com.rpl.mastodonapi.MastodonApiApplication.main(MastodonApiApplication.java:41)
Caused by: java.lang.StackOverflowError
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$some.invokeStatic(core.clj:2709)
        at clojure.core$some_fn$spn__8780.invoke(core.clj:7536)
        at clojure.core$complement$fn__5737.invoke(core.clj:1455)
        at rpl.rama.util.parse$fn__35581$item_test__35602$fn__35603.invoke(parse.clj:12)
        at clojure.algo.monads$state_t$m_bind_state_t__35559$fn__35560$fn__35561.invoke(monads.clj:675)
        at clojure.algo.monads$fn__35333$m_bind_maybe__35336.invoke(monads.clj:364)
        at clojure.algo.monads$state_t$m_bind_state_t__35559$fn__35560.invoke(monads.clj:675)
        at clojure.algo.monads$state_t$m_bind_state_t__35559$fn__35560.invoke(monads.clj:675)
        at clojure.algo.monads$state_t$fn__35567$fn__35568$fn__35569.invoke(monads.clj:686)
        at clojure.core$map$fn__5935.invoke(core.clj:2772)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
`

**Comment by nathanmarz** [comment]
What version of Java are you using?

**Comment by dipenappscrip** [comment]
openjdk 11.0.20.1 

![image](https://github.com/redplanetlabs/twitter-scale-mastodon/assets/82133137/a970bc95-e3f9-4b66-afda-3458ca738fed)

**Comment by DotKhalid** [comment]
facing same error 
root@ubuntu-s-2vcpu-4gb-blr1-01:~/paki/api# java -version
openjdk version "17.0.9-ea" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9-ea+6-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 17.0.9-ea+6-Ubuntu-1, mixed mode, sharing)

**Comment by nathanmarz** [comment]
Another user ran into this before and fixed it by explicitly setting the stack size. Can you try running it like this?

```
mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xss2m"
```

**Comment by DotKhalid** [comment]
thanks for your answer but I'm trying to from last three days 
<img width="811" alt="browser" src="https://github.com/redplanetlabs/twitter-scale-mastodon/assets/50384210/50897ab2-61f7-4f55-8c46-85ce5ee618db">
facing this issue what I have to give in instance localhost not working my domain name not working also ip not working
