### ISSUE TITLE
Error - Read a frame size of 218762506, which is bigger than the maximum allowable frame size 16384000 for ALL connections

### ISSUE THREAD

**Issue by dipenappscrip** [redplanetlabs/twitter-scale-mastodon#4]
![image](https://github.com/redplanetlabs/twitter-scale-mastodon/assets/82133137/4f448ab3-5430-4afd-90c6-b66b274ee6ca)

How can i solve this ?

**Comment by dipenappscrip** [comment]
getting this on browser 
![image](https://github.com/redplanetlabs/twitter-scale-mastodon/assets/82133137/5c606551-d54b-4b87-85c9-73d711aad5cb)

**Comment by nathanmarz** [comment]
We would need more information about how you're running this to be able to help:

- What version of Java?
- What OS?
- How did you launch the backend and frontend?
- Are there any other errors in the developer tools of your browser?
- Is there anything else in the console logs for the backend?
- What endpoint were you trying to hit when you got that error?
