### ISSUE TITLE
Unable to start RAMA on port 8080

### ISSUE THREAD

**Issue by dipenappscrip** [redplanetlabs/twitter-scale-mastodon#5]
![image](https://github.com/redplanetlabs/twitter-scale-mastodon/assets/82133137/9cf22d45-b0a6-4399-b681-0fb4dd9fffc9)
![image](https://github.com/redplanetlabs/twitter-scale-mastodon/assets/82133137/21c9af76-c196-4a62-94f2-e656b36591e4)
![Uploading image.png…]()

I am getting this logs but unable to start RAMA

cmd -  mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xss4m"

**Comment by dipenappscrip** [comment]
I am unable to run RAMA on port : 8080

**Comment by nathanmarz** [comment]
Rama isn't running on port 8080. It's the Spring API server that runs on that port.

Without more information I'm unable to help you any further. I would take a look at any WARN or ERROR logs, or if there's something else on your machine running on that port.
