### ISSUE TITLE
unable to run twitter-scale-mastodon with  soapbox

### ISSUE THREAD

**Issue by dipenappscrip** [redplanetlabs/twitter-scale-mastodon#6]
![image](https://github.com/redplanetlabs/twitter-scale-mastodon/assets/82133137/d9cf9671-115c-45b9-9c6c-e73adf85bb1d)
![image](https://github.com/redplanetlabs/twitter-scale-mastodon/assets/82133137/ca876e5c-d979-49b4-9958-b4bcb601bbc3)
![image](https://github.com/redplanetlabs/twitter-scale-mastodon/assets/82133137/9ac9cb12-43a8-45cf-b6bc-77b4cd7c2f13)
![image](https://github.com/redplanetlabs/twitter-scale-mastodon/assets/82133137/830552a1-d6b7-4d4c-9e6e-db1eb0e0b3a3)

**Comment by nathanmarz** [comment]
I have no idea unfortunately why Soapbox isn't building properly for you. The JS ecosystem can be very touchy. Other than a few minor patches to Soapbox, we mostly just used it unchanged. I suggest directing any questions about building Soapbox to the main Soapbox repository, as the actual developers of Soapbox will be able to be much more helpful.
