### ISSUE TITLE
Can't sign in to the rama backend! Tried the given user accounts as well

### ISSUE THREAD

**Issue by SyedMahadAsif** [redplanetlabs/twitter-scale-mastodon#7]
![rama](https://github.com/redplanetlabs/twitter-scale-mastodon/assets/151061294/d1a30d9b-7c4f-4e34-a8db-17aeea52c983)

**Comment by nathanmarz** [comment]
That indicates that the backend hasn't launched properly. What is the log about when you launch the backend?

**Comment by SyedMahadAsif** [comment]
![Uploading Screenshot from 2023-12-08 12-37-07.png…]()

**Comment by nathanmarz** [comment]
All I see you in your comment is `Uploading Screenshot from 2023-12-08 12-37-07.png…`
